SDK-245 [Python SDK] Add non hashing mode for key1-key10
incountry/sdk-python pull request #129
Opened 2020-11-17 18:22 UTC by RommeroInCountry

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-245](https://incountry.atlassian.net/browse/SDK-245)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2020-11-18 16:24 UTC, VladimirLevitskiy approved these changes
LGTM

2020-11-18 16:48 UTC, VladimirLevitskiy submitted a review, later dismissed

2020-11-19 09:21 UTC, artemgolozubov requested changes
The rest LGTM

2020-11-19 09:21 UTC, artemgolozubov commented on tests/unit/test_crypto_utils.py
> +        print(key, normalize, key_value_before, key_value_after)
Please remove this print() call

2020-11-19 11:26 UTC, artemgolozubov approved these changes
LGTM

2020-11-19 13:37 UTC, VladimirLevitskiy approved these changes

2020-11-20 13:02 UTC, merged