DEVOPS-2470: Print bandit issues to travis console
incountry/sdk-python pull request #135
Opened 2020-12-14 13:58 UTC by ihar-adzinets-incountry

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- https://incountry.atlassian.net/browse/DEVOPS-2470

2020-12-14 14:10 UTC, RommeroInCountry commented
Please make this PR into develop :) SDK uses master as live branch :)

2020-12-14 14:14 UTC, RommeroInCountry requested changes

2020-12-14 14:14 UTC, RommeroInCountry commented on travis-build.sh
> +pip3 install bandit && bandit --ini bandit.ini -r -o bandit.json -f json --exclude './venv,./test,./.gitlint-rules,./queue_worker/test,./queue_watcher/test,./scripts'
SDK uses ./tests as testing folder, not test.
Please also add setup.py to bandit exclude as well

2020-12-15 07:32 UTC, daniilyar-incountry commented on travis-build.sh
> +pip3 install bandit && bandit --ini bandit.ini -r -o bandit.json -f json --exclude './venv,./test,./.gitlint-rules,./queue_worker/test,./queue_watcher/test,./scripts'
The command 
```
bandit --ini bandit.ini -r -o bandit.json -f json --exclude
```

Should not be executed twice

2020-12-15 08:47 UTC, daniilyar-incountry approved these changes

2020-12-15 14:19 UTC, RommeroInCountry approved these changes

2020-12-15 16:20 UTC, merged