SDK-254 [Python SDK] AWS KMS Key integration example
incountry/sdk-python pull request #142
Opened 2021-01-29 14:48 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-254](https://incountry.atlassian.net/browse/SDK-254)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version? What is the new version?

2021-02-08 14:00 UTC, igor-alekseev-dev submitted a review, later dismissed

2021-02-09 16:53 UTC, VladimirLevitskiy requested changes

2021-02-09 16:53 UTC, VladimirLevitskiy commented on examples/aws-kms.py
> +        "body": json.dumps({"test": "Test AWS KMS keys in Node.js SDK"}),
Please change the record body to '...Python SDK...'

2021-02-10 09:48 UTC, VladimirLevitskiy approved these changes
LGTM

2021-03-11 13:06 UTC, RommeroInCountry requested changes

2021-03-11 13:06 UTC, RommeroInCountry commented on examples/aws-kms.py
> +    decoded_key = base64.b64encode(decrypted_key).decode("utf8")
decrypted_key is already of bytes type. Python SDK allows bytes to be used as key straight away. No need to do all these transformations

2021-03-23 15:44 UTC, RommeroInCountry approved these changes

2021-04-13 13:01 UTC, VladimirLevitskiy approved these changes
LGTM

2021-04-13 13:13 UTC, merged