SDK-289 [Python SDK] add Schema 2.3 support
incountry/sdk-python pull request #143
Opened 2021-02-03 11:50 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-289](https://incountry.atlassian.net/browse/SDK-289)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version? What is the new version?

2021-03-23 14:57 UTC, RommeroInCountry requested changes

2021-03-23 14:57 UTC, RommeroInCountry commented on tests/unit/test_compatibility.py
> +    (  # schema 2.3
please use data from SDK Node.js https://github.com/incountry/sdk-nodejs/blob/master/tests/unit/storage/compatibility-tests.ts
The idea behind these tests is to have the very same prepared data for all SDKs (see prev data pieces - they are identical)

2021-03-24 11:06 UTC, RommeroInCountry approved these changes

2021-03-29 14:13 UTC, VladimirLevitskiy approved these changes
LGTM

2021-03-29 14:29 UTC, merged