SDK-295 [Python SDK] Sorting support
incountry/sdk-python pull request #153
Opened 2021-03-29 13:29 UTC by RommeroInCountry

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-295](https://incountry.atlassian.net/browse/SDK-295)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-03-30 13:16 UTC, VladimirLevitskiy requested changes

2021-03-30 13:16 UTC, VladimirLevitskiy commented on incountry/storage.py
>                  - profile_key, service_key1, service_key2, key1, ..., key10.
key10 -> key20

2021-03-30 13:16 UTC, VladimirLevitskiy commented on incountry/storage.py
>                  - profile_key, service_key1, service_key2, key1, ..., key10,
the same, key10 -> key20

2021-03-30 13:16 UTC, VladimirLevitskiy commented on incountry/storage.py
> +            sort: Sort filter.
Please add a section to the README

2021-04-01 10:54 UTC, VladimirLevitskiy requested changes

2021-04-01 10:54 UTC, VladimirLevitskiy commented on README.md
> +SDK currently supports sorting by `key1...key20`, `range_key1...range_key10` keys.
What about date fields?

2021-04-01 17:22 UTC, artemgolozubov reviewed
Pls take a look at the comments below

2021-04-01 17:22 UTC, artemgolozubov commented on tests/unit/storage/test_enpoint_countries_endpoint.py
> +import json
Pls fix a typo in filename

2021-04-01 17:22 UTC, artemgolozubov commented on README.md
> +To use `sort` in find() call for string keys `key1...key20` you need to set  `hashSearchKeys` option to `false`.
```suggestion
To use `sort` in find() call for string keys `key1...key20` you need to set  `hash_search_keys` option to `False`.
```

2021-04-08 15:32 UTC, RommeroInCountry commented on README.md
> +SDK currently supports sorting by `key1...key20`, `range_key1...range_key10` keys.
Thanks for noticing

2021-04-08 15:35 UTC, RommeroInCountry commented on incountry/models/sort_filter.py
> +class SortFilter(BaseModel):
my bad

2021-04-09 12:00 UTC, artemgolozubov approved these changes
LGTM

2021-04-09 12:12 UTC, VladimirLevitskiy approved these changes

2021-04-13 12:27 UTC, merged