SDK-303 [Python SDK] Allow oAuth2 token Storage initialization
incountry/sdk-python pull request #164
Opened 2021-05-12 10:59 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-303](https://incountry.atlassian.net/browse/SDK-303)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version? What is the new version?

2021-05-13 10:12 UTC, RommeroInCountry requested changes
let's move this PR further and include API Key removal as well. 
We can skip 3.5.0 release in favour of 4.0.0

2021-05-13 10:12 UTC, RommeroInCountry commented on incountry/models/storage_with_env.py
> +                f"Please choose either authorization with previously acquired oAuth token or oAuth authorization by "
authorization using oAuth token or authorization using oAuth credentials (client_id + client_secret), not both

2021-05-24 13:04 UTC, RommeroInCountry requested changes

2021-05-24 13:17 UTC, artemgolozubov commented on incountry/storage.py
> +                OAuth token which is already acquired prior to Storage initialization.
@RommeroInCountry It's just a copy-paste from Node SDK Readme file. See https://github.com/incountry/sdk-nodejs/commit/c7ae1867dab570fc34846703fe1481605c3e290e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R50
Are you sure we need to change this text here?

2021-05-24 14:03 UTC, RommeroInCountry commented on incountry/storage.py
> +                OAuth token which is already acquired prior to Storage initialization.
Then we'd better update text in Node SDK as well :D it's just to excessive right now

2021-05-26 12:37 UTC, RommeroInCountry submitted a review, later dismissed

2021-05-28 11:56 UTC, igor-alekseev-dev commented on incountry/models/storage_with_env.py
> +                f"Please choose either authorization using oAuth token or authorization using oAuth "
I think this needs to be rephrased

2021-05-28 11:57 UTC, igor-alekseev-dev approved these changes

2021-07-29 11:18 UTC, RommeroInCountry approved these changes

2021-07-29 14:03 UTC, merged