SDK-468 [Python SDK] add caching support for /countries data
incountry/sdk-python pull request #198
Opened 2021-11-23 10:44 UTC by RommeroInCountry

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-468](https://incountry.atlassian.net/browse/SDK-468)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-11-25 10:16 UTC, VladimirLevitskiy requested changes

2021-11-25 10:16 UTC, VladimirLevitskiy commented on incountry/countries_cache.py
> +    DEFAULT_CACHE_TTL = 60
300 seconds are used in other SDKs

2021-11-25 10:16 UTC, VladimirLevitskiy commented on incountry/countries_cache.py
> +            self.update_countries_cache()
Make it failsafe. If PB returns an empty country list response, use previous countries cache

2021-11-25 10:30 UTC, RommeroInCountry commented on incountry/countries_cache.py
> +            self.update_countries_cache()
@VladimirLevitskiy completely ignore if /countries response validation fails?

2021-11-30 14:06 UTC, VladimirLevitskiy submitted a review, later dismissed

2021-12-06 13:57 UTC, VladimirLevitskiy approved these changes

2021-12-07 10:17 UTC, artemgolozubov approved these changes
LGTM

2021-12-07 10:56 UTC, merged