SDK-429 [Python SDK] .find() silently omits inexistent filter key
incountry/sdk-python pull request #206
Opened 2022-01-27 10:58 UTC by RommeroInCountry

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-429](https://incountry.atlassian.net/browse/SDK-429)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2022-02-07 14:04 UTC, artemgolozubov approved these changes
LGTM

2022-02-10 14:24 UTC, vrodochenko-incountry commented on incountry/retry.py
> +                    total_retries = total_retries + 1
probably should leave the "try" block to focus on what actually can fail

2022-02-10 14:26 UTC, vrodochenko-incountry commented on incountry/retry.py
> +                    ):
is it possible to raise "StorageServerException" with no "status_code"? Consider adding it to the error if you want it

2022-02-10 14:28 UTC, vrodochenko-incountry commented on incountry/retry.py
>  from random import random
why not use tenacity's (https://github.com/jd/tenacity) "retry" functionality?

2022-02-10 14:44 UTC, RommeroInCountry commented on incountry/retry.py
> +                    ):
this component is just for retries with specific status_code. If Exception doesn't have one - no retries should be made

2022-02-10 15:57 UTC, artemgolozubov commented on incountry/retry.py
> +                    ):
@vrodochenko-incountry According to the diagram https://incountry.atlassian.net/wiki/spaces/A/pages/847577097/NodeJS+SDK+Error+handling+from+v3.4.0 (which is for Node but afaik it doesn't matter - Python SDK has the similar inheritance structure for errors classes) we may have "StorageServerException" with no "status_code"

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry requested changes
Consider some changes

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/validation/validate_model.py
>                  new_kwargs[key] = validated_data_dict[key]
Another way to do it. Not sure which is clearer, but I think it's prettier (we update `new_kwargs` here):
```python
        new_kwargs.update(
            (key, validated_data_dict[key])
            for key in new_kwargs
            if key in validated_data_dict
        )
```

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/validation/validate_model.py
> +    return reduce(lambda agg, field_name: f"{agg} \n  {field_name} - extra fields not permitted", extra_fields, "")
Pythonic way to do that (also it will probably reduce number of allocations):
```suggestion
    return " \n  ".join(
        f"{field_name} - extra fields not permitted"
        for field_name in extra_fields
    )
```

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/validation/utils.py
>      )
Also consider add function:
```python
    def format_index(index):
        return index if isinstance(index, int) else f"'{index}'"

...

        rest_lines_formatted="".join(
            f"[{format_index(idx)}]"
            for idx in rest_lines
        )
```

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/retry.py
> +            class_instance = args[0] if "self" in signature(function).parameters else None
Consider to use `inspect.ismethod` here

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/retry.py
> +                    should_execute = False
PyCharm says: Local variable 'should_execute' value is not used
```suggestion
```

Consider to use:
```python
           while True:
```
And get rid of `should_execute` and `total_retries`

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/retry.py
> +                    should_execute = False
Or maybe we are missing logic associated with `total_retries`?

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/retry.py
> +            max_delay_sec = retry_max_delay(class_instance) if callable(retry_max_delay) else retry_max_delay
In case `class_instance` is `None` we should provide lambda like this?
```python
retry_base_delay=lambda _: some_heavy_operation(),
```
It would be cleaner if we could use this decorator like this:
```python
@retry_on_server_exception(
    status_code=429,
    retry_base_delay=some_heavy_operation,
    retry_max_delay=some_heavy_operation_2,
)
def request_without_self():
     ...
```
Instead of:
```python
@retry_on_server_exception(
    status_code=429,
    retry_base_delay=lambda _: some_heavy_operation(),
    retry_max_delay=lambda _: some_heavy_operation_2(),
)
def request_without_self():
     ...
```

2022-02-14 13:42 UTC, sviatoslav-alekseev-incountry commented on incountry/retry.py
> +                    ):
What's the point of using `getattr(e, "status_code", None)` twice here? `StorageServerException` has a `status_code` field in `__init__`, which means it must be in `e` and have type `Optional[int]`. I would suggest simplify it like this: 
```python
                    if e.status_code != status_code:
                        raise
```

2022-02-15 10:29 UTC, RommeroInCountry commented on incountry/retry.py
> +                        raise
Nope. The design was to do a retry on a proper status code and to not interfere in any other case

2022-02-15 10:31 UTC, RommeroInCountry commented on tests/unit/test_validation.py
> +    test_function(test_kwargs["arg1"], test_kwargs["arg2"], test_kwargs["arg3"], test_kwargs["arg4"])
not really. the test check that our own validate_model decorator works properly both for args and for kwargs

2022-02-15 15:36 UTC, RommeroInCountry commented on incountry/storage.py
> +        return getattr(self.options, option, None) is True
this one was advised by Sonar I believe. 
And, imho, it's has better readability this way (in that particular context where it's used)

2022-02-15 15:59 UTC, sviatoslav-alekseev-incountry commented on incountry/storage.py
> +        return getattr(self.options, option, None) is True
Ok, resolved

2022-02-15 16:13 UTC, RommeroInCountry commented on incountry/retry.py
> +                    should_execute = False
yeah, total_retries can be removed - some obsolete code here

2022-02-15 16:14 UTC, RommeroInCountry commented on incountry/retry.py
> +                    should_execute = False
As for should_execute - PyCharm kinda lies. It's used for the decorator to decide whether to retry function execution after exception or not.

2022-02-15 16:16 UTC, RommeroInCountry commented on incountry/retry.py
> +                    should_execute = False
But yeah, looks like should_execute can be dropped and logical order of execution will not suffer any issues

2022-02-15 17:47 UTC, sviatoslav-alekseev-incountry requested changes
Some other suggestions

2022-02-15 17:47 UTC, sviatoslav-alekseev-incountry commented on incountry/validation/validate_model.py
> +            f"{format_extra_fields_error(set(new_kwargs.keys()).difference(model_fields_set))}"
`dict_keys` implement `__sub__`, so we could simplify it without additional reallocation like this:
```suggestion
            f"{format_extra_fields_error(new_kwargs.keys() - model_fields_set)}"
```

2022-02-15 17:47 UTC, sviatoslav-alekseev-incountry commented on incountry/validation/validate_model.py
> +            f"{format_extra_fields_error(set(new_kwargs.keys()).difference(model_fields_set))}"
[issubset](https://docs.python.org/3/library/stdtypes.html#frozenset.issubset) is also implemented by `dict_keys`

2022-02-15 17:47 UTC, sviatoslav-alekseev-incountry commented on tests/unit/storage/test_find_find_one.py
> +    enc_data = [client(encrypt).encrypt_record(dict(x)) for x in records]
I think we could reuse client instance here and get rid of `dict` copying:
```python
    client_instance = client(encrypt)
    enc_data = [client_instance.encrypt_record(record) for record in records]
    
    ...

    client_instance.find.when.called_with(country=COUNTRY, **query).should.throw(InputValidationException)
```

2022-02-17 16:06 UTC, sviatoslav-alekseev-incountry commented on incountry/validation/validate_model.py
> +    if args and len(args) and args[0] and ismethod(getattr(args[0], function.__name__, None)):
It should be `tuple` actually

2022-02-18 14:21 UTC, artemgolozubov approved these changes
LGTM

2022-02-18 15:09 UTC, VladimirLevitskiy approved these changes

2022-02-18 15:11 UTC, vrodochenko-incountry commented on incountry/retry.py
> +                        current_delay_sec = current_delay_sec * 2
you may want to make "2" an adjustable thing ;)

2022-02-18 15:12 UTC, vrodochenko-incountry commented on incountry/retry.py
> +                        current_delay_sec = current_delay_sec * 2
or, even better -- implement an https://en.wikipedia.org/wiki/Exponential_backoff

2022-02-18 15:16 UTC, vrodochenko-incountry commented on incountry/validation/validate_encryption_enabled.py
> +                f"This method is only allowed with encryption enabled"
```suggestion
                f"This method is only allowed with encryption enabled"
```
And this is why we use flake8: this f-string does nothing

2022-02-18 15:18 UTC, vrodochenko-incountry commented on tests/unit/test_validation.py
> +    test_kwargs = {"arg1": "random_str", "arg2": 123, "arg3": False, "arg4": "test"}
there are args and there are kwargs, the naming
````python
kwargs = [arg1, arg2]
```
is slightly confusing, IMHO

2022-02-18 15:21 UTC, vrodochenko-incountry commented
But none of the above are approve-breakers, ofc. Overall, looks better!

2022-02-21 10:25 UTC, RommeroInCountry commented on tests/unit/test_validation.py
> +    test_kwargs = {"arg1": "random_str", "arg2": 123, "arg3": False, "arg4": "test"}
will make a note for it ;)

2022-02-21 10:31 UTC, RommeroInCountry commented on incountry/validation/validate_encryption_enabled.py
> +                f"This method is only allowed with encryption enabled"
I'd vote for keeping as is just for consistency. Anyway - will read more on this and try to figure out why the issue wasn't raised by flake8

2022-02-21 10:31 UTC, merged